[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Schappo1612", email = "gustavoschappo1612@gmail.com"},
]
dependencies = [
    "django>=4.2.5",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

