# Generated by Django 4.2.5 on 2023-09-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_fornecedor_produtos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
