# Generated by Django 4.2.5 on 2023-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_remove_produtos_fornecedor_produtos_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='site',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
