# Generated by Django 4.2.5 on 2023-09-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('academia', '0005_alter_fornecedor_options_alter_fornecedor_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='capa',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='claudio',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='claudio',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='Fornecedor',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='academia.fornecedor'),
            preserve_default=False,
        ),
    ]
