# Generated by Django 4.2.6 on 2023-11-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0014_rename_titulo_produtos_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='nome',
            new_name='titulo',
        ),
    ]
